# Generated by Django 6.0.6 on 2026-07-06 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Curso')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código del Curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Tema / Título de la Lección')),
                ('id_url', models.SlugField(help_text='ID corto para la URL. Ej: carga-electrica o combinaciones', max_length=100, unique=True)),
                ('universidad', models.CharField(default='Universidad Mariano Gálvez de Guatemala', max_length=200)),
                ('facultad', models.CharField(default='Facultad de Ingeniería en Sistemas', max_length=200, verbose_name='Facultad / Escuela')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='lessons.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Lección / Tema',
                'verbose_name_plural': 'Lecciones / Temas',
            },
        ),
        migrations.CreateModel(
            name='Diapositiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Número o posición de la diapositiva (1, 2, 3...)')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Diapositiva')),
                ('contenido', models.TextField(verbose_name='Contenido (Soporta código HTML o texto plano)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='diaporamas/', verbose_name='Imagen de soporte (Opcional)')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diapositivas', to='lessons.leccion')),
            ],
            options={
                'verbose_name': 'Diapositiva',
                'verbose_name_plural': 'Diapositivas',
                'ordering': ['orden'],
            },
        ),
    ]
